#!/usr/ bin/ env bash 
# Check if an IP address is provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the command line argument
ip_address=$1

# Perform ping with 5 attempts
ping -c 5 $ip_address
